import React from 'react'
import { FormattedMessage, injectIntl, Link } from 'gatsby-plugin-intl'
import { Container, Row, Col, Jumbotron } from 'react-bootstrap'
import { Offline, Online } from 'react-detect-offline'
import QRCode from 'qrcode.react'

import Layout from '@components/layout'
import VideoStream from '@components/element/videoStream'

import SEO from "@components/helper/seo"

const Try = ({ intl }) => {
  // SET THE DEMO URL,
  // QR code gets generated by its own.
  const demoURL = 'https://nba.snapscreen.com/'
  return (
    <Layout>
      <SEO
        lang={intl.locale}
        title={intl.formatMessage({ id: "page.try.title" })}
        description={intl.formatMessage({ id: "page.try.description" })}
      />
      <Jumbotron>
        <Offline>
          <Container>
            <Row>
              <Col xs="12" md="10" lg="5" className="ml-auto mr-auto">
                <div className="text-center p-3">
                  <svg xmlns='http://www.w3.org/2000/svg' width='128' height='128' viewBox='0 0 512 512'>
                    <title><FormattedMessage id={"offline.status"} /></title>
                    <path d='M93.72,183.25C49.49,198.05,16,233.1,16,288c0,66,54,112,120,112H320.37' style={{fill: 'none', stroke: '#fff', strokeLinecap: 'round', strokeLinejoin:'round', strokeWidth:'32px'}} />
                    <path d='M467.82,377.74C485.24,363.3,496,341.61,496,312c0-59.82-53-85.76-96-88-8.89-89.54-71-144-144-144-26.16,0-48.79,6.93-67.6,18.14' style={{fill: 'none', stroke: '#fff', strokeLinecap: 'round', strokeLinejoin: 'round', strokeWidth:'32px'}} />
                    <line x1='448' y1='448' x2='64' y2='64' style={{fill:'none', stroke: '#fff', strokeLinecap: 'round', strokeMiterlimit:10, strokeWidth: '32px'}}/>
                  </svg>
                </div>
                <h1 className="display-2 my-4 py-4 text-center" style={{minHeight: 0}}>
                  <strong><FormattedMessage id={"offline.text"} /></strong>
                </h1>
                <p className="lead text-center">
                  <FormattedMessage id={"offline.cta"} />
                </p>
              </Col>
            </Row>
          </Container>
        </Offline>
        <Online>
          <Container>
            <Row>
              <Col>
                <h1 className="display-2 my-4 py-4 text-center" style={{minHeight: 0}}>
                  <strong><FormattedMessage id={"page.try.headline"} />!</strong>
                </h1>
              </Col>
            </Row>
            <Row>
              <Col xs="12" md="10" lg="5" className="ml-auto mr-auto">
                <ol className="lead mb-4">
                  <li>
                    <p>
                      <strong><FormattedMessage id={"page.try.howTo1emphasize"} /></strong>{" "}
                      <FormattedMessage id={"page.try.howTo1text"} />{" "}
                      <a href={demoURL} target="_blank" rel="noopener noreferrer">{demoURL}</a>
                    </p>
                  </li>
                  <li>
                    <p>
                      <strong><FormattedMessage id={"page.try.howTo2emphasize"} /></strong>{" "}
                      <FormattedMessage id={"page.try.howTo2text"} />{" "}
                      <span role="img" aria-label="smile">😉</span>
                    </p>
                  </li>
                </ol>
              </Col>
              <Col xs="12" md="10" lg="7" className="mx-auto py-3">
                <Row className="align-items-center mb-4">
                  <Col xs="4" sm="3" md="3" className="ml-auto">
                      <QRCode
                        value={demoURL}
                        renderAs={"svg"}
                        className="ml-auto p-2 bg-white img-thumbnail"
                       />
                  </Col>
                  <Col xs="2" sm="1" md="1" className="my-auto">
                    <ion-icon size="large" name="phone-portrait-outline" style={{color: "#ffffff", display: "inline-flex"}} />
                  </Col>
                  <Col xs="6" sm="6" md="7" className="mr-auto">
                    <p className="mt-4">
                      <FormattedMessage id={"page.try.instruction"} />
                    </p>
                  </Col>
                </Row>
              </Col>
            </Row>
            <Row className="">
              <Col md="10" lg="8" className="mx-auto my-4 py-4">
                <VideoStream id="Aw3xFO1wdJ4" autoplay="1" mute="1" />
              </Col>
            </Row>
            <Row>
              <Col md="10" lg="8" className="mx-auto mt-4">
                <h2 className="my-4 text-center"><strong><FormattedMessage id={"page.try.endline"} /></strong></h2>
                <p className="text-center my-4"><strong><FormattedMessage id={"page.try.engagement"} /></strong></p>
                <div className="pt-4 text-center">
                  <Link to="/contact" className="btn btn-primary btn-lg mt-2 mt-sm-0">
                    <FormattedMessage id="action.contact" />
                  </Link>
                  <Link to="/solution" className="btn btn-link btn-lg mx-sm-2 mt-2 mt-sm-0">
                    <FormattedMessage id="action.solution" />
                  </Link>
                </div>
              </Col>
            </Row>
          </Container>
        </Online>
      </Jumbotron>
    </Layout>
  )
}

export default injectIntl(Try)
